name: Build and Push phpfpm Image

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Login to Docker Hub
        run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
      
      - name: Build the Docker image
        run: docker build . --file Dockerfile --tag php-fpm:$(date +%s)

      - name: Push Docker image
        run: docker push php-fpm:$(date +%s)
