name: Build and Push phpfpm Image

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Login to Docker Hub
        run: echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin
      
      - name: Build the Docker image
        run: docker build . --file ./web/php-fpm/Dockerfile --tag php-fpm:latest

      - name: Push Docker image
        run: docker tag php-fpm:latest php-fpm:$(date +%s) # 使用与构建相同的标签
      - run: docker push php-fpm:$(date +%s)
