name: Build and Push phpfpm Image

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Login to Docker Hub
        run: echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin
      
      - name: Build the Docker image
        run: docker build . --file ./web/php-fpm/Dockerfile --tag php-fpm:latest # 使用 "latest" 标签或其他自定义标签

      - name: Push Docker image
        run: |
          docker tag php-fpm:latest ${{ secrets.DOCKER_USERNAME }}/php-fpm:latest
          docker push ${{ secrets.DOCKER_USERNAME }}/php-fpm:latest
