[M"aCversion: '3.8'

services:
  nginx:
    image: nginx
    container_name: nginx
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./conf.d:/etc/nginx/conf.d
      - ./certs:/etc/nginx/certs
      - ./html:/var/www/html

  php:
    image: squarelo/php-fpm
    container_name: php
    restart: always
    volumes:
      - ./html:/var/www/html

  php74:
    image: squarelo/php74-fpm
    container_name: php74
    restart: always
    volumes:
      - ./html:/var/www/html

  mysql:
    image: mysql
    container_name: mysql
    restart: always
    volumes:
      - ./mysql:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: squareloPASS
      MYSQL_USER: squarelo
      MYSQL_PASSWORD: squareloPASS

  redis:
    image: redis
    container_name: redis
    restart: always
    volumes:
      - ./redis:/data
